# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKucx2PJskFzgPSNYeD4dRBJM5XBwhX3
"""

! pip install Streamlit

import streamlit as st

# عنوان التطبيق
st.title('مرحبًا بك في تطبيق Streamlit')

# نص تفاعلي
st.write('هذا تطبيق بسيط باستخدام Streamlit!')

# إضافة مدخل للمستخدم
name = st.text_input('أدخل اسمك:')
if name:
    st.write(f'مرحبًا {name}!')

