# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKucx2PJskFzgPSNYeD4dRBJM5XBwhX3
"""

#! pip install Streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# تحميل البيانات من ملف CSV
sdf = pd.read_csv('data.csv')

# حساب المتوسط حسب المنطقة
avg_exp_by_region = sdf.groupby('region')['exper_years'].mean()

# إعداد واجهة المستخدم في Streamlit
st.title('متوسط سنوات الخبرة حسب المنطقة')
st.write("رسم بياني لعرض متوسط سنوات الخبرة في مختلف المناطق")

# رسم البياني باستخدام Matplotlib
plt.figure(figsize=(10, 6))
plt.bar(avg_exp_by_region.index, avg_exp_by_region.values, color='skyblue')
plt.xlabel('المنطقة')
plt.ylabel('متوسط سنوات الخبرة')
plt.title('متوسط سنوات الخبرة حسب المنطقة')

# عرض الرسم البياني في Streamlit
st.pyplot(plt)

